name: Generate Lunar Calendar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node index.js

      - run: ls -lah   # 🔍 检查是否生成 calendar.ics

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add calendar.ics
          git commit -m "add calendar" || echo "no changes"
          git push
